name: build-gh-pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout symbiflow-database-visualizer
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Checkout prjxray-db
        uses: actions/checkout@v2
        with:
          repository: SymbiFlow/prjxray-db
          path: external_repos/prjxray-db

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install node packages
        run: |
          npm install

      - name: Build app bundle and data files
        run: |
          export PRJXRAYDB_DIR="$(realpath external_repos/prjxray-db)"
          ./utils/build-all.sh

      - name: Deploy page
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/production/
          CLEAN: true
